{% set name = "asap" %}
{% set version = "3.10.6" %}
{% set sha256 = "9018d26030fa34e84a0404dd3292973a6067a7a90528531a33b8584b5fdc52b1" %}
{% set asap_version = "3_10_6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-ASAP_VERSION_{{ asap_version }}-afc2473cfb8cf89b5e88189e0fdffa0f40d3efc7.tar.gz
  url: https://gitlab.com/{{ name }}/{{ name }}/repository/archive.tar.gz?ref=ASAP_VERSION_{{ asap_version }}
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - ase

test:
  imports:
    - asap3

about:
  home: https://gitlab.com/asap/asap
  license: GPL-3.0
  license_file: LICENSE
  summary: 'ASAP is a calculator for doing large-scale molecular dynamics (MD)
  within the Atomic Simulation Environment.'

  description: |
    ASAP is a calculator for doing large-scale molecular dynamics (MD) within
    the Atomic Simulation Environment. The focus of ASAP is on solid-state
    physics (as opposed to molecular chemistry), and in particular metallic
    systems.

  doc_url: https://wiki.fysik.dtu.dk/asap/asap
  dev_url: https://gitlab.com/asap/asap

extra:
  recipe-maintainers:
    - CJ-Wright
