appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: PZCXQe6vGp/AjvmRjK+I4Y6AhBTxqay8tYMpYzapZYtn9rQ93T8mSOcm1VYeFU05iyfmV72idTlsrdyDh9f2tpO19K3eY9yJVFUc9rDnyhcrE/CRXmQTbqvkvZsQIKtdknO9lgfrLTSuvIoJ4yl39SPGGutlE8nzlBRdgs6CCURxPqBz9VcFzgRzpW9mR6rko3+sxCkHbjvFZvC001WKQCX81Iq1nmLq8mcjiVpGVB5JEjwqWqET7cuMPnrccdj2Q7S37CbF9l9nLygP01GhHysetk2TLsDfHW0IzYE3EurBcC3NQqdelBXNo3hMGpF3wS59o1HvDvWsQuswR8DiI3XpM9mTQo1MXJg3tCCSqXQR+6fPxZE3bghS1z3goqSvca3VukE2ByY6iVuv1DuwJ5epxCln4gg4bPYi9TTycDEMl2iYnFbsiRrXsz078rvqD5cqmLTQixFXM8TFHkolhEQ44PEVbWJ9IDgKaZUCmW9PkQbpSCTHNWMhGsbmvikg/KRHZIzsQyCNUIS7fh/+lB6S81Dz7LNT8JDrF2btD1UjJO8akale9+nxdih4z5RmaAQZ29bCvapWDQU2lAfdyG6384X/mfkwjXr6LjNL7ilVlfLus7RXrNezk7vdDEEOsaAYTDSRKQcjCMQwj7QJOFwsTeSkfpQd9frT56DXNyY=}
